#document settings
title: Document Title Here
description: Document Description
url: http://project-open-data.github.com/open-licenses
repo_url: https://github.com/project-open-data/open-licenses

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true