#document settings
title: Open Licenses
description: The standard set of open licenses for the United States Government
url: http://project-open-data.github.com/open-licenses
repo_url: https://github.com/project-open-data/open-licenses

# default build settings for running locally, no need to edit
server: auto
safe: true
pymgemnts: true
auto: true